language: node_js
node_js:
  - "12.0"
dist: trusty
sudo: required

branches:
  only:
    - main

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - ng build --prod --base-href https://gwas.github.io/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/gwas-blog
  on:
    branch: main
