language: node_js
node_js:
  - "12.0"
dist: trusty
sudo: required

cache:
  directories:
    - 'node_modules'
    -
branches:
  only:
    - main

before_script:
  - npm install

script:
  - echo "Skipping tests"
  - npm run generate

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
